---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/,

---
spring:
  profiles: subject
words: I,You,He,She,I
server:
  port: 9004
 
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
server:
  port: 9005

---
spring:
  profiles: article
words: a,the
server:
  port: 9002

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: 9001

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
server:
  port: 9003
  
  ---
spring:
  profiles: eureka-primary
server:
  port: 8011
  
    ---
spring:
  profiles: eureka-secondary
server:
  port: 8012
  
      ---
spring:
  profiles: eureka-tertiary
server:
  port: 8013
  
  
  
