---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary.responsible-nrg.com,http://eureka-secondary.responsible-nrg.com,http://eureka-tertiary.responsible-nrg.com
      
# Allow Eureka to recognize two apps of the same type 
# on the same host as separate instances (see bonus step):
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
---
spring:
  profiles: nothamerica
lucky-word: "The Golden Horse Shoe"
server:
  port: 8012
---
spring:
  profiles: sentence
server:
  port: 8020
management: 
  endpoints: 
    web: 
      exposure: 
        include: 'hystrix.stream'
---
spring:
  profiles: word
# Note: all properties defined in this file are subject to replacement by the configuration server.
words: foo,bar,baz
server:
  port: 8030
---
spring:
  profiles: subject
words: I,You,He,She,It
server:
  port: 9004
 
---
spring:
  profiles: verb
words: ran,knew,had,saw,bought
server:
  port: 9005

---
spring:
  profiles: article
words: a,the
server:
  port: 9002

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely
server:
  port: 9001

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog
server:
  port: 9003
  
---  
spring:
  profiles: cold-noun
words: icicle,refrigerator,blizzard,snowball
server:
  port: 9013

---
spring:
  profiles: eureka-primary
server:
  port: 8011
eureka:
  client:
    serviceUrl:
       defaultZone: http://eureka-secondary.responsible-nrg.com,http://eureka-tertiary.responsible-nrg.com

---
spring:
  profiles: eureka-secondary
server:
  port: 8012
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary.responsible-nrg.com,http://eureka-tertiary.responsible-nrg.com
  
---
spring:
  profiles: eureka-tertiary
server:
  port: 8013
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary.responsible-nrg.com,http://eureka-secondary.responsible-nrg.com
